  php:
services:
    build: .
    volumes:
      - ./project/public:/var/www/html
      - ./config.php:/var/www/config.php
      - ./.env:/var/www/.env
      - ./vendor:/var/www/vendor
    ports:
      - '8080:80'
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  mysql:
    container_name: entry_php_mysql_container
    image: mysql:8.3
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    restart: always
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    links:
      - mysql
    ports:
       - '8060:80'
    volumes:
       - /sessions
volumes:
  mysql_data:
